# Generated by Django 3.2.8 on 2021-10-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_emp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=230)),
                ('tipo_persona_emp', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigo_est', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_est', models.CharField(max_length=230)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('codigo_mod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'modulo',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('codigo_nom', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechainicio_nom', models.DateField()),
                ('fechafin_nom', models.DateField()),
                ('salariobase_nom', models.BigIntegerField(blank=True, null=True)),
                ('salariodeduccion_nom', models.BigIntegerField(blank=True, null=True)),
                ('salariodevengo_nom', models.BigIntegerField(blank=True, null=True)),
                ('salariototal_emp', models.BigIntegerField(blank=True, null=True)),
                ('codigo_emp', models.ForeignKey(db_column='codigo_emp', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.empleado')),
                ('codigo_estado_nom', models.ForeignKey(db_column='codigo_estado_nom', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.estado')),
            ],
            options={
                'db_table': 'nomina',
                'unique_together': {('codigo_nom', 'codigo_emp')},
            },
        ),
        migrations.CreateModel(
            name='Tiponovedad',
            fields=[
                ('codigo_tipnov', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipnov', models.CharField(max_length=250)),
                ('tipoconcepto_tipnov', models.CharField(max_length=10)),
                ('valorbase_tipnov', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiponovedad',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('codigo_nov', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_nov', models.BigIntegerField()),
                ('codigo_nom', models.ForeignKey(db_column='codigo_nom', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.nomina')),
                ('codigo_tipnov', models.ForeignKey(db_column='codigo_tipnov', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.tiponovedad')),
            ],
            options={
                'db_table': 'novedad',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('codigo_ing', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_nom', models.ForeignKey(db_column='codigo_nom', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.nomina')),
                ('codigo_nov', models.ForeignKey(db_column='codigo_nov', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.novedad')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='codigo_mod',
            field=models.ForeignKey(db_column='codigo_mod', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.modulo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_estado_emp',
            field=models.ForeignKey(db_column='codigo_estado_emp', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.estado'),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('codigo_des', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_nom', models.ForeignKey(db_column='codigo_nom', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.nomina')),
                ('codigo_nov', models.ForeignKey(db_column='codigo_nov', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.novedad')),
            ],
            options={
                'db_table': 'descuento',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('codigo_con', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo_cont', models.CharField(max_length=250)),
                ('salario_con', models.BigIntegerField()),
                ('fechainicio_con', models.DateField(blank=True, null=True)),
                ('fechafin_con', models.DateField(blank=True, null=True)),
                ('tipo_con', models.CharField(max_length=25)),
                ('codigo_emp', models.ForeignKey(db_column='codigo_emp', on_delete=django.db.models.deletion.DO_NOTHING, to='authApp.empleado')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
