# Generated by Django 3.2.8 on 2021-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='codigo_mod',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='codigo_nom',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='codigo_nov',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='codigo_estado_emp',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='codigo_estado_nom',
        ),
        migrations.AddField(
            model_name='nomina',
            name='estado_nom',
            field=models.CharField(default=1, max_length=230),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Descuento',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
