# Generated by Django 3.2.8 on 2021-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211026_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado_emp',
            field=models.CharField(default='ACTIVO', max_length=230),
            preserve_default=False,
        ),
    ]
