# Generated by Django 3.2.8 on 2021-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_nomina_estado_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='estado_nom',
            field=models.CharField(choices=[('liquidada', 'liquidada'), ('pre-liquidada', 'pre-liquidada')], max_length=20),
        ),
    ]
