from .empleadoCreateView import EmpleadoCreateView
from .empleadoDeleteView import EmpleadoDeleteView
from .empleadoGetView import EmpleadoGetView
from .empleadoUpdateView import EmpleadoUpdateView
from .nominaCreateView import NominaCreateView
from .nominaUpdateView import NominaUpdateView
from .nominaDetailview import NominaDetailView
from .novedadDeleteView import NovedadDeleteView
from .novedadListView import NovedadListView
from .tiponovedadCreateView import TipoNovedadCreateView
from .tiponovedadUpdateView import TiponovedadUpdateView
from .tipoNovedadConsultarView import TipoNovedadListView
from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .empleadoDetailView import EmpleadoDetailView
